apiVersion: v2
name: billing-service
description: A Helm chart for Billing Service
type: application
version: 0.0.1
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
    tags:
      - billingdb
