{
 "title": "API Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "user-profile-service,auth-service,order-service,billing-service,notification-service,product-service,price-service,product-search-service,warehouse-service,delivery-service"
   }
  ]
 },
 "panels": [
  { "title": "API Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "apiKey" },
  {
   "title": "Latency (Q 0.5)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (apiKey, le) (rate(otus_architect_requests_latency_bucket{service=\"$service\"}[1m]))) * 1000\n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  {
   "title": "Latency (Q 0.95)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (apiKey, le) (rate(otus_architect_requests_latency_bucket{service=\"$service\"}[1m]))) * 1000\n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  {
   "title": "Latency (Q 0.99)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (apiKey, le) (rate(otus_architect_requests_latency_bucket{service=\"$service\"}[1m]))) * 1000\n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  {
   "title": "Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (apiKey, le) (rate(otus_architect_requests_latency_bucket{service=\"$service\"}[1m]))) * 1000\n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (apiKey) (rate(otus_architect_requests_total{service=\"$service\"}[1m])) \n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (apiKey) (increase(otus_architect_requests_total{service=\"$service\",status=~\"5..\"}[1m])) \n",
     "legendFormat": "{{apiKey}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"$service-.*\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (rate(container_memory_working_set_bytes{pod=~\"$service-.*\"}[1m])) ",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}