{
 "title": "API Nginx",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency (Q 0.5)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"krakend\"}[1m]))) * 1000\n",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "Latency (Q 0.95)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"krakend\"}[1m]))) * 1000\n",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "Latency (Q 0.99)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"krakend\"}[1m]))) * 1000\n",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "Latency (Max)",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"krakend\"}[1m]))) * 1000\n",
     "legendFormat": "Total Latency"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"krakend\"}[1m])) \n",
     "legendFormat": "Total RPS"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"krakend\",status=~\"5..\"}[1m])) \n",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}