{{- $svcPort := .Values.service.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "otus-architect.fullname" . }}
  labels:
    {{- include "otus-architect.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "otus-architect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "otus-architect.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ $svcPort }}
              protocol: TCP
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: otus-architect-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: otus-architect-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: otus-architect-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: otus-architect-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: otus-architect-config
                  key: DB_NAME
          livenessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ $svcPort }}
            initialDelaySeconds: {{ .Values.health.initialDelay }}
            periodSeconds: {{ .Values.health.periodSeconds }}
            timeoutSeconds: {{ .Values.health.timeoutSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.health.path }}
              port: {{ $svcPort }}
            initialDelaySeconds: {{ .Values.health.initialDelay }}
            periodSeconds: {{ .Values.health.periodSeconds }}
            timeoutSeconds: {{ .Values.health.timeoutSeconds }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
