apiVersion: v2
name: otus-architect
description: A Helm chart for Kubernetes
type: application
version: 0.3.5
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgres.enabled
    tags:
      - otus-architect-database
