apiVersion: v1
kind: ConfigMap
metadata:
  name: user-profile-config
data:
  DB_HOST: {{ (include "postgresql.fullname" .) | quote }}
  DB_PORT: {{ .Values.postgresql.service.port | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | quote }}
  AUTH_REALM: {{ .Values.jwt.realm | quote }}
  AUTH_PUBLIC_KEY_FILE: {{ .Values.jwt.publicKeyFile | quote }}
  AUTH_PRIVATE_KEY_FILE: {{ .Values.jwt.privateKeyFile | quote }}
  AUTH_ISSUER: {{ .Values.jwt.issuer | quote }}
  AUTH_AUDIENCE: {{ .Values.jwt.audience | quote }}
  KAFKA_READER_HOST: {{ .Values.kafka.reader.host | quote }}
  KAFKA_READER_PORT: {{ .Values.kafka.reader.port | quote }}
  KAFKA_WRITER_HOST: {{ .Values.kafka.writer.host | quote }}
  KAFKA_WRITER_PORT: {{ .Values.kafka.writer.port | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: user-profile-secret
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
